# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fls < Formula
  desc "fls produces paletted black and white images using the Floyd-Steinberg dithering algorithm"
  homepage "https://github.com/sub-mersion/fls"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sub-mersion/fls/releases/download/v0.1.1/fls_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "aaec2445d2530d88901eee68e5ea8c00fbad5062852d625d2521cb45fee53e29"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sub-mersion/fls/releases/download/v0.1.1/fls_0.1.1_Linux_x86_64.tar.gz"
      sha256 "de8f132fe20b7483338a382497f128b120f2adb2e3b447c95a04be4d5972f0fa"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sub-mersion/fls/releases/download/v0.1.1/fls_0.1.1_Linux_arm64.tar.gz"
      sha256 "451fdf51c8413292026e3a1de6c6edf79a58f8e9369352ba6c92677ec2370c81"
    end
  end

  def install
    bin.install "fls"
  end
end
